# Pesa solo ~2MB y tiene certificados para conectar a la DB
FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY target/backofficeAPI /app/backofficeAPI

# Puerto dinámico de Render
ENV SERVER_PORT=${PORT}
ENV TZ=Europe/Madrid

USER 1000:1000

ENTRYPOINT ["/app/backofficeAPI"]